name: practice

on:
  push: 
  
permissions:
  id-token: write
  contents: read
  
jobs:
  azure_login:
    name: az login
    runs-on: ubuntu-latest
    steps:
       - name: Checkout
         uses: actions/checkout@v6.0.3
       - name: Azure Login
         uses: Azure/login@v3
         with:
           creds: ${{secrets.AZURE_CREDENTIALS}}
       - name: run az cli
         run: az account show


            
