name: practice

on:
  workflow_dispatch:

jobs:
  my_first_job:
    name: my first job
    runs-on: ubuntu-latest
    steps:
      - name: Greetings
        run: echo "Hello Pandey"
      - name: list files
        run: ls -la
env:
  FIRST_NAME: NAHID
env:
  LAST_NAME: ALI
  second_job:
      - name: Greetings
        run: echo "Hello $FIRST_NAME $LAST_NAME"
        
   
