name: practice

on:
  workflow_dispatch:
env:
  FIRST_NAME: NAHID
  LAST_NAME: ALI
  
jobs:
  my_first_job:
    name: my first job
    runs-on: ubuntu-latest
    steps:
       - name: Checkout
         uses: actions/checkout@v6.0.3
       - name: Greetings
         run: echo "Hello Pandey"
       - name: list files
         run: ls -la
  second_job:
    name: second job
    runs-on: ubuntu-latest
    steps:
      - name: greetings
        run: echo "Hello #FIRST_NAME $LAST_NAME"



            
   
